// <auto-generated />
using System;
using EduAtendance.WebAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduAtendance.WebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250828170914_mg5")]
    partial class mg5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EduAtendance.WebAPI.Models.MenuTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MenuTemplates");
                });

            modelBuilder.Entity("EduAtendance.WebAPI.Models.MenuTemplateSubmenu", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("MenuTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ParentId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Title");

                    b.HasIndex("MenuTemplateId");

                    b.HasIndex("ParentId");

                    b.ToTable("MenuTemplateSubmenu");
                });

            modelBuilder.Entity("EduAtendance.WebAPI.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("EduAtendance.WebAPI.Models.SurveyTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SurveyTemplates");
                });

            modelBuilder.Entity("EduAtendance.WebAPI.Models.MenuTemplateSubmenu", b =>
                {
                    b.HasOne("EduAtendance.WebAPI.Models.MenuTemplate", null)
                        .WithMany("Submenus")
                        .HasForeignKey("MenuTemplateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EduAtendance.WebAPI.Models.MenuTemplateSubmenu", null)
                        .WithMany("Submenus")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsMany("EduAtendance.WebAPI.Models.MenuTemplateSubmenuItems", "Items", b1 =>
                        {
                            b1.Property<string>("SubmenuId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("SubmenuId", "Id");

                            b1.ToTable("MenuTemplateSubmenuItems");

                            b1.WithOwner()
                                .HasForeignKey("SubmenuId");
                        });

                    b.Navigation("Items");
                });

            modelBuilder.Entity("EduAtendance.WebAPI.Models.SurveyTemplate", b =>
                {
                    b.OwnsMany("EduAtendance.WebAPI.Models.SurveyTemplateCategory", "Categories", b1 =>
                        {
                            b1.Property<Guid>("SurveyTemplateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("SurveyTemplateId", "Id");

                            b1.ToTable("SurveyTemplateCategory");

                            b1.WithOwner()
                                .HasForeignKey("SurveyTemplateId");

                            b1.OwnsMany("EduAtendance.WebAPI.Models.SurveyTemplateCategoryOption", "Options", b2 =>
                                {
                                    b2.Property<Guid>("SurveyTemplateCategorySurveyTemplateId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("SurveyTemplateCategoryId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("SurveyTemplateCategorySurveyTemplateId", "SurveyTemplateCategoryId", "Id");

                                    b2.ToTable("SurveyTemplateCategoryOption");

                                    b2.WithOwner()
                                        .HasForeignKey("SurveyTemplateCategorySurveyTemplateId", "SurveyTemplateCategoryId");
                                });

                            b1.OwnsMany("EduAtendance.WebAPI.Models.SurveyTemplateCategoryQuestion", "Questions", b2 =>
                                {
                                    b2.Property<Guid>("SurveyTemplateCategorySurveyTemplateId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("SurveyTemplateCategoryId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("SurveyTemplateCategorySurveyTemplateId", "SurveyTemplateCategoryId", "Id");

                                    b2.ToTable("SurveyTemplateCategoryQuestion");

                                    b2.WithOwner()
                                        .HasForeignKey("SurveyTemplateCategorySurveyTemplateId", "SurveyTemplateCategoryId");
                                });

                            b1.Navigation("Options");

                            b1.Navigation("Questions");
                        });

                    b.Navigation("Categories");
                });

            modelBuilder.Entity("EduAtendance.WebAPI.Models.MenuTemplate", b =>
                {
                    b.Navigation("Submenus");
                });

            modelBuilder.Entity("EduAtendance.WebAPI.Models.MenuTemplateSubmenu", b =>
                {
                    b.Navigation("Submenus");
                });
#pragma warning restore 612, 618
        }
    }
}
